name: 02-business-workflow
on: 
  - push:
  - pull_request:
  - workflow_dispatch:
  - schedule:
      - cron: '0/5 0 * * *'

jobs:
  job-event-reporter:
    runs-on: ubuntu-latest
    steps:
      - name: report-jobs
        run: echo 'This job gets triggered by the event - ${{github.event_name}}' 
