name: 03-environment-vars
run-name: 03-environment-variables.yaml Demo

on:
  push:
  workflow_dispatch:

env:
  MY_VAR: Workflow Level
  MY_VAR_OVERWRITTEN: Workflow Level overwrite

jobs:
  echo_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Vars at Job level
        run: echo " THis is my environment variable ${{vars.MY_VAR}}"      
